site:
  title: Bryce's 官方网站
  description: Bryce's books, reading notes, blogs and more.
  keywords: Bryce, books, reading, blogs, productivity, IT, English, Python, AI, quant, life, PO, PM
  theme: default
  language: en-US
  # set the /<rootPath> pathname under which your site is served
  # for GitHub pages deployment without a custom domain, it is often '/<projectName>'
  # root-path: /gitsite
  # set cdn path:
  cdn-path: https://cdn.jsdelivr.net/npm
  navigation:
    - title: 利器
      uri: /books/productivity/index.html
    - title: 思考
      uri: /books/think/index.html
    - title: 读书
      uri: /books/reading/index.html  
    - title: 投资
      uri: /books/Invest/index.html
#    - title: 产品
#      uri: /books/PO and PM/index.html
    - title: 英语
      uri: /books/English/index.html
    - title: 生活
      uri: /books/life/index.html
    - title: 育儿
      uri: /books/KidGrow/index.html
    - title: AI
      uri: /books/AI/index.html
#    - title: IT
#      uri: /books/Corp IT Infra/index.html
    - title: Python
      uri: /books/python/index.html
    - title: Swift
      uri: /books/Swift/index.html
    - title: Blog
      uri: /blogs/tech/index.html
    - title: Links
      uri: /pages/links/index.html
#    - title: Discuss
#      uri: https://github.com/michaelliao/gitsite/discussions
#      external: true
#  git:
#    base-url: https://github.com/michaelliao/gitsite/blob/main/source
  contact:
    name: Bryce Li
    github: https://github.com/abnceo
    twitter: https://twitter.com/liaoxuefeng
  books:
    index-marker: true
  search:
    # none = no search
    # browser = flex search in browser
    # google = google site search
    type: browser
  # control styles:
  styles:
    # show 'Edit in Git':
    display-git-link: true
    # any custom styles used in theme:
    # code-font: Monaco
  integration:
    comment:
      provider: disqus
      name: gitsite
    analytics:
      provider: 
      gtag: 

build:
  # copy special files under root dir (ignore if not found):
  copy:
    - favicon.ico
    - robots.txt
    - ads.txt

# you can add any items:
